server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    include: db,mp
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,/swagger-ui.html

logging:
  level:
    root: info
    org.fivesoft.appresources: debug
  file:
    name: logs/log.log

