spring:
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0